version: '3.4'

networks:
  default:
    external:
      name: pcicbr0
  jupyterhub_network:
    external:
      name: jupyterhub_network
services:
  geoserver:
    volumes:
    - /storage/data/projects/comp_support/geoserver-test-data-dir/geoserver-2.15.0/data_dir:/opt/geoserver/data_dir
    - /storage/data/projects/comp_support/geoserver-test-data-dir/webapps_geoserver_web-info_web.xml:/opt/geoserver/webapps/geoserver/WEB-INF/web.xml
  thredds:
    volumes:
      - /storage/data/projects/comp_support/climate_explorer_data_prep/climatological_means:/pavics-ncml/storage/data/projects/comp_support/climate_explorer_data_prep/climatological_means
      - /storage/data/climate/downscale/BCCAQ2/bccaqv2_with_metadata:/pavics-ncml/storage/data/climate/downscale/BCCAQ2/bccaqv2_with_metadata
      - /storage/data/projects/hydrology/dataportal/CMIP5/VICGL:/pavics-ncml/storage/data/projects/hydrology/dataportal/CMIP5/VICGL
      - /storage/data/climate/downscale/CMIP5/BCCAQ:/pavics-ncml/storage/data/climate/downscale/CMIP5/BCCAQ
      - /storage/data/climate/downscale/CMIP5/BCSD:/pavics-ncml/storage/data/climate/downscale/CMIP5/BCSD
      - /storage/data/climate/downscale/BCCAQ2/CMIP6_BCCAQv2:/pavics-ncml/storage/data/climate/downscale/BCCAQ2/CMIP6_BCCAQv2
      - /storage/data/climate/hydrology/vic/gen1/output:/pavics-ncml/storage/data/climate/hydrology/vic/gen1/output
      - /storage/data/projects/dataportal/data/vic_gen1_input:/pavics-ncml/storage/data/projects/dataportal/data/vic_gen1_input
      - /storage/data/projects/dataportal/data/vic-gen2-forcing:/pavics-ncml/storage/data/projects/dataportal/data/vic-gen2-forcing
      - /storage/data/projects/dataportal/data/hydrology/vic_gen1_followup/vic_gen1_routed:/pavics-ncml/storage/data/projects/dataportal/data/hydrology/vic_gen1_followup/vic_gen1_routed
      - /storage/data/projects/dataportal/data/hydrology/vic_cmip5/merged:/pavics-ncml/storage/data/projects/dataportal/data/hydrology/vic_cmip5/merged
      - /storage/data/climate/downscale/BCCAQ2/ANUSPLIN/climatologies:/pavics-ncml/storage/data/climate/downscale/BCCAQ2/ANUSPLIN/climatologies
      - /storage/data/projects/hydrology/vic_gen2:/pavics-ncml/storage/data/projects/hydrology/vic_gen2
      - /storage/data/climate/PRISM/dataportal:/pavics-ncml/storage/data/climate/PRISM/dataportal
      - /storage/data/projects/comp_support/daccs/test-data:/pavics-ncml/storage/data/projects/comp_support/daccs/test-data
      - /storage/data/projects/comp_support/climate_explorer_data_prep/hydro/sample_data/set4:/pavics-ncml/storage/data/projects/comp_support/climate_explorer_data_prep/hydro/sample_data/set4
      - /storage/data/climate/observations/gridded/PRISM:/pavics-ncml/storage/data/climate/observations/gridded/PRISM
#  testthredds:
#    volumes:
#      - /storage/data/projects/hydrology/vic_gen2:/pavics-testdata/storage/data/projects/hydrology/vic_gen2
