version: '3.4'

services:
  chickadee-dev:
    image: ${CHICKADEE_DEV_IMAGE}
    container_name: chickadee-dev
    environment:
      - PYWPS_CFG=/wps.cfg
    ports:
      - "30102:5000"
    volumes:
      - ${BIRDHOUSE_CONFIG_DIR}/files/chickadee/birdhouse-component/wps.cfg:/wps.cfg
      - wps_outputs:/data/wpsoutputs
      - /tmp
    restart: always

  magpie:
    volumes:
    - ${BIRDHOUSE_CONFIG_DIR}/files/chickadee/birdhouse-component/chickadee-magpie-permission.cfg:/opt/local/src/magpie/config/permissions/chickadee-magpie-permission.cfg:ro
    - ${BIRDHOUSE_CONFIG_DIR}/files/chickadee/birdhouse-component/chickadee-magpie-provider.cfg:/opt/local/src/magpie/config/providers/chickadee-magpie-provider.cfg:ro

  canarie-api:
    volumes:
      - ${BIRDHOUSE_CONFIG_DIR}/files/chickadee/birdhouse-component/chickadee_canarie_api_monitoring.py:${CANARIE_MONITORING_EXTRA_CONF_DIR}/chickadee_canarie_api_monitoring.py:ro
