version: '3.4'
services:
  osprey:
    image: ${OSPREY_IMAGE}
    container_name: osprey
    environment:
      - PYWPS_CFG=/wps.cfg
      - LISTENER_HOST=0.0.0.0
      - GUNICORN_TIMEOUT=0
      - GUNICORN_WORKERS=10
    ports:
      - "8100:5000"
    expose:
      - "5005-5014"
    volumes:
      - ${BIRDHOUSE_CONFIG_DIR}/osprey/birdhouse-component/wps.cfg:/wps.cfg
      - wps_outputs:/data/wpsoutputs
      - /tmp
    restart: always
    networks:
      - pcicbr1 # Network with osprey-flask-app

  magpie:
    volumes:
    - ${BIRDHOUSE_CONFIG_DIR}/osprey/birdhouse-component/osprey-magpie-permission.cfg:/opt/local/src/magpie/config/permissions/osprey-magpie-permission.cfg:ro
    - ${BIRDHOUSE_CONFIG_DIR}/osprey/birdhouse-component/osprey-magpie-provider.cfg:/opt/local/src/magpie/config/providers/osprey-magpie-provider.cfg:ro

  canarie-api:
    volumes:
      - ${BIRDHOUSE_CONFIG_DIR}/osprey/birdhouse-component/osprey_canarie_api_monitoring.py:${CANARIE_MONITORING_EXTRA_CONF_DIR}/osprey_canarie_api_monitoring.py:ro

networks:
  pcicbr1:
    external: true
