version: '3.4'
services:
  quail:
    image: ${QUAIL_IMAGE}
    container_name: quail
    environment:
      - PYWPS_CFG=/wps.cfg
    ports:
      - "8103:5000"
    volumes:
      - ${BIRDHOUSE_CONFIG_DIR}/files/quail/birdhouse-component/wps.cfg:/wps.cfg
      - wps_outputs:/data/wpsoutputs
      - /tmp
    restart: always

  magpie:
    volumes:
    - ${BIRDHOUSE_CONFIG_DIR}/files/quail/birdhouse-component/quail-magpie-permission.cfg:/opt/local/src/magpie/config/permissions/quail-magpie-permission.cfg:ro
    - ${BIRDHOUSE_CONFIG_DIR}/files/quail/birdhouse-component/quail-magpie-provider.cfg:/opt/local/src/magpie/config/providers/quail-magpie-provider.cfg:ro

  canarie-api:
    volumes:
      - ${BIRDHOUSE_CONFIG_DIR}/files/quail/birdhouse-component/quail_canarie_api_monitoring.py:${CANARIE_MONITORING_EXTRA_CONF_DIR}/quail_canarie_api_monitoring.py:ro
